services:
  tt-scrap:
    build: .
    image: ghcr.io/karilaa-dev/tt-scrap:latest
    env_file:
      - .env
    environment:
      YTDLP_COOKIES: /run/secrets/cookies.txt
      PROXY_FILE: /run/secrets/proxies.txt
    volumes:
      - ./cookies.txt:/run/secrets/cookies.txt:ro
      - ./proxies.txt:/run/secrets/proxies.txt:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
